version: '3.9'

services:
  api:
    build:
      dockerfile: docker\Dockerfile
      context: .
    ports:
      - '9001:9001'
      - '9002:9002'
    networks:
      - express
    container_name: express-api
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    container_name: express_postgres
    env_file:
      - .env
    networks:
      - express
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 7772:5432

networks:
  express:
    driver: bridge

volumes:
  database:
