version: '3.9'

services:
  api:
    build:
      dockerfile: docker\Dockerfile-Production
      context: .
      target: prod
    ports:
      - '9009:9009'
    networks:
      - express
    container_name: express-api
    depends_on:
      - db
    env_file:
      - .env.production

  db:
    image: postgres:15.1-alpine
    container_name: express_postgres
    env_file:
      - .env.production
    networks:
      - express
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 7772:5432

networks:
  express:
    driver: bridge

volumes:
  database:
